# .github/workflows/ollama.yml
on: workflow_dispatch
jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ollama
        uses: ai-action/setup-ollama@v2

      - name: Run model
        run: ollama run gemma4:e2b 'What model are you?'
