on: workflow_dispatch
env:
  OLLAMA_CONTEXT_LENGTH: 131072
  # MODEL_NAME: qwen3:4b
  # MODEL_NAME: glm4:9b  # context exceeded
  # MODEL_NAME: deepseek-v2:16b  # context exceeded
  # MODEL_NAME: qwen3.5:9b
  # MODEL_NAME: gemma4:12b
  MODEL_NAME: gemma4:e2b

jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Ollama
        uses: ai-action/setup-ollama@v2

      - run: ollama pull $MODEL_NAME

      - uses: actions/setup-python@v7
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - run: uv sync

      - run: uv run main.py

      - run: ollama ps
        if: always()

      - uses: actions/upload-artifact@v7
        with:
          name: response
          path: main.py.json

      - run: cat main.py.json