on: workflow_dispatch
env:
  MODEL_NAME: gemma4:e2b

jobs:
  ollama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ai-action/setup-ollama@v2

      - run: ollama pull $MODEL_NAME

      - uses: actions/setup-python@v7
        with:
          python-version: v3.14

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - run: uv sync

      - run: uv run main.py
